package cc.wecando.miuihook.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorMethods = listOf(
    cc.wecando.miuihook.mirror.com.miui.permcenter.install.Methods,
    cc.wecando.miuihook.mirror.android.os.Methods
)
