package cc.wecando.miuihook.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorClasses = listOf(
    cc.wecando.miuihook.mirror.com.miui.permcenter.install.Classes,
    cc.wecando.miuihook.mirror.android.os.Classes

)
