package cc.wecando.miuihook.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorFields = listOf(
    cc.wecando.miuihook.mirror.com.miui.permcenter.privacymanager.Fields,
    cc.wecando.miuihook.mirror.com.miui.permcenter.install.Fields,
)
