package cc.wecando.miuihook

import cc.wecando.miuihook.backend.FuckAdbInstallDialog
import cc.wecando.miuihook.backend.FuckSpecialDialog


/**
 * Dynamically generated by build.gradle
 */
val Plugins = listOf(FuckAdbInstallDialog, FuckSpecialDialog)
