package cc.wecando.antim

import cc.wecando.antim.backend.FuckAdbInputApply
import cc.wecando.antim.backend.FuckAdbInstallDialog
import cc.wecando.antim.backend.FuckSpecialDialog


/**
 * Dynamically generated by build.gradle
 */
val Plugins = listOf(FuckAdbInstallDialog, FuckSpecialDialog, FuckAdbInputApply)
