package cc.wecando.antim.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorClasses = listOf(
    cc.wecando.antim.mirror.com.miui.permcenter.install.Classes,
    cc.wecando.antim.mirror.com.miui.permcenter.privacymanager.Classes,
    cc.wecando.antim.mirror.com.miui.antivirus.activity.Classes,
    )
