package cc.wecando.antim.mirror

/**
 * Dynamically generated by build.gradle
 */
val MirrorFields = listOf(
    cc.wecando.antim.mirror.com.miui.permcenter.privacymanager.Fields,
    cc.wecando.antim.mirror.com.miui.permcenter.install.Fields,
)
